# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/managam/Specs.git'

target 'Curlistswift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Curlistswift

  pod 'MSSwiftScraper', :path => '../../MSSwiftScraper/'

  target 'CurlistswiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurlistswiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
